"""add permission_requests table

Revision ID: 850b0bc5b144
Revises: 068d1db9bca5
Create Date: 2026-07-08 21:28:22.328117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850b0bc5b144'
down_revision: Union[str, None] = '068d1db9bca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('requested_role', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_override_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_override_id'], ['user_permission_overrides.override_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_permission_requests_pending_unique', 'permission_requests', ['requester_id', 'permission_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_permission_requests_requester_id'), 'permission_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_permission_requests_status'), 'permission_requests', ['status'], unique=False)
    # ### end Alembic commands ###
    # Note: autogenerate also detected the same pre-existing, unrelated
    # 'role_permissions.role_name' column drift noted in
    # 068d1db9bca5_add_user_permission_overrides_table.py — left
    # untouched here too, still out of scope for this migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permission_requests_status'), table_name='permission_requests')
    op.drop_index(op.f('ix_permission_requests_requester_id'), table_name='permission_requests')
    op.drop_index('ix_permission_requests_pending_unique', table_name='permission_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('permission_requests')
    # ### end Alembic commands ###
