"""add sla tables

Revision ID: 317e5570c7df
Revises: c3e5a7f9b1d4
Create Date: 2026-07-11 17:50:22.213037

Also seeds the three sla_policies rows (one per TicketPriority) with
the targets confirmed for this rollout:
  HIGH:   24h first response / 3 days (4320 min) resolution
  MEDIUM: 48h first response / 5 days (7200 min) resolution
  LOW:    72h first response / 7 days (10080 min) resolution
Fixed UUIDs (not regenerated per run) so this migration is safe to
read/reason about and re-run deterministically against a fresh DB,
matching alembic_rbac's categories-table seed migration.
"""

import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '317e5570c7df'
down_revision: Union[str, None] = 'c3e5a7f9b1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ticket_priority_enum already exists (created by the very first
# ticketing migration for tickets.current_priority) — every column
# below that reuses it must pass create_type=False, or SQLAlchemy
# tries (and fails, DuplicateObject) to CREATE TYPE again for each
# table that references it. sla_clock_status_enum is brand new for
# this migration: created once by the first table that uses it
# (resolution_slas), then referenced with create_type=False by every
# later table (first_response_slas) so it isn't created twice either.
TICKET_PRIORITY_ENUM = postgresql.ENUM(
    "LOW", "MEDIUM", "HIGH", name="ticket_priority_enum", create_type=False
)


def _sla_clock_status_enum(*, create_type: bool) -> postgresql.ENUM:
    return postgresql.ENUM(
        "PENDING",
        "RUNNING",
        "PAUSED",
        "COMPLETED",
        name="sla_clock_status_enum",
        create_type=create_type,
    )


SLA_POLICY_SEED = [
    {
        "policy_id": uuid.UUID("2f6a5e9c-6b3e-4b58-9b3b-2d9f2a6e1a10"),
        "priority": "HIGH",
        "first_response_target_minutes": 24 * 60,
        "resolution_target_minutes": 3 * 24 * 60,
    },
    {
        "policy_id": uuid.UUID("7d3c8f21-9a4e-4a2b-9d5b-4e7c1b2a8f31"),
        "priority": "MEDIUM",
        "first_response_target_minutes": 48 * 60,
        "resolution_target_minutes": 5 * 24 * 60,
    },
    {
        "policy_id": uuid.UUID("c1a9b4d6-2e5f-4c7a-8b1d-9f3e6a4c2b52"),
        "priority": "LOW",
        "first_response_target_minutes": 72 * 60,
        "resolution_target_minutes": 7 * 24 * 60,
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sla_breach_notifications',
    sa.Column('sla_breach_notification_id', sa.UUID(), nullable=False),
    sa.Column('clock_type', sa.String(length=20), nullable=False),
    sa.Column('clock_id', sa.UUID(), nullable=False),
    sa.Column('threshold', sa.String(length=20), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sla_breach_notification_id')
    )
    op.create_index('ix_sla_breach_notifications_unique', 'sla_breach_notifications', ['clock_type', 'clock_id', 'threshold'], unique=True)
    op.create_table('sla_policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('priority', TICKET_PRIORITY_ENUM, nullable=False),
    sa.Column('first_response_target_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_target_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('resolution_slas',
    sa.Column('resolution_sla_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('priority', TICKET_PRIORITY_ENUM, nullable=False),
    sa.Column('status', _sla_clock_status_enum(create_type=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_paused_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('resolution_sla_id')
    )
    op.create_index(op.f('ix_resolution_slas_client_id'), 'resolution_slas', ['client_id'], unique=False)
    op.create_index(op.f('ix_resolution_slas_due_at'), 'resolution_slas', ['due_at'], unique=False)
    op.create_index(op.f('ix_resolution_slas_status'), 'resolution_slas', ['status'], unique=False)
    op.create_index('ix_resolution_slas_status_due_at', 'resolution_slas', ['status', 'due_at'], unique=False)
    op.create_index(op.f('ix_resolution_slas_ticket_id'), 'resolution_slas', ['ticket_id'], unique=True)
    op.create_table('first_response_slas',
    sa.Column('first_response_sla_id', sa.UUID(), nullable=False),
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('priority', TICKET_PRIORITY_ENUM, nullable=False),
    sa.Column('status', _sla_clock_status_enum(create_type=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_reason', sa.String(length=30), nullable=True),
    sa.Column('resulting_ticket_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.interaction_id'], ),
    sa.ForeignKeyConstraint(['resulting_ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('first_response_sla_id')
    )
    op.create_index(op.f('ix_first_response_slas_client_id'), 'first_response_slas', ['client_id'], unique=False)
    op.create_index(op.f('ix_first_response_slas_due_at'), 'first_response_slas', ['due_at'], unique=False)
    op.create_index(op.f('ix_first_response_slas_interaction_id'), 'first_response_slas', ['interaction_id'], unique=True)
    op.create_index(op.f('ix_first_response_slas_status'), 'first_response_slas', ['status'], unique=False)
    op.create_index('ix_first_response_slas_status_due_at', 'first_response_slas', ['status', 'due_at'], unique=False)
    op.create_table('resolution_sla_pause_intervals',
    sa.Column('pause_interval_id', sa.UUID(), nullable=False),
    sa.Column('resolution_sla_id', sa.UUID(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pause_reason', sa.String(length=30), nullable=False),
    sa.Column('triggering_interaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolution_sla_id'], ['resolution_slas.resolution_sla_id'], ),
    sa.ForeignKeyConstraint(['triggering_interaction_id'], ['interactions.interaction_id'], ),
    sa.PrimaryKeyConstraint('pause_interval_id')
    )
    op.create_index(op.f('ix_resolution_sla_pause_intervals_resolution_sla_id'), 'resolution_sla_pause_intervals', ['resolution_sla_id'], unique=False)
    op.create_index('ix_resolution_sla_pause_intervals_sla_id_paused_at', 'resolution_sla_pause_intervals', ['resolution_sla_id', 'paused_at'], unique=False)
    # ### end Alembic commands ###

    # Seed the three per-priority SLA policy rows — see this module's
    # own docstring for the confirmed target values.
    sla_policies_table = sa.table(
        'sla_policies',
        sa.column('policy_id', sa.UUID()),
        sa.column('priority', TICKET_PRIORITY_ENUM),
        sa.column('first_response_target_minutes', sa.Integer()),
        sa.column('resolution_target_minutes', sa.Integer()),
        sa.column('is_active', sa.Boolean()),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )

    now = datetime.now(timezone.utc)
    op.bulk_insert(
        sla_policies_table,
        [
            {
                "policy_id": row["policy_id"],
                "priority": row["priority"],
                "first_response_target_minutes": row["first_response_target_minutes"],
                "resolution_target_minutes": row["resolution_target_minutes"],
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            }
            for row in SLA_POLICY_SEED
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resolution_sla_pause_intervals_sla_id_paused_at', table_name='resolution_sla_pause_intervals')
    op.drop_index(op.f('ix_resolution_sla_pause_intervals_resolution_sla_id'), table_name='resolution_sla_pause_intervals')
    op.drop_table('resolution_sla_pause_intervals')
    op.drop_index('ix_first_response_slas_status_due_at', table_name='first_response_slas')
    op.drop_index(op.f('ix_first_response_slas_status'), table_name='first_response_slas')
    op.drop_index(op.f('ix_first_response_slas_interaction_id'), table_name='first_response_slas')
    op.drop_index(op.f('ix_first_response_slas_due_at'), table_name='first_response_slas')
    op.drop_index(op.f('ix_first_response_slas_client_id'), table_name='first_response_slas')
    op.drop_table('first_response_slas')
    op.drop_index(op.f('ix_resolution_slas_ticket_id'), table_name='resolution_slas')
    op.drop_index('ix_resolution_slas_status_due_at', table_name='resolution_slas')
    op.drop_index(op.f('ix_resolution_slas_status'), table_name='resolution_slas')
    op.drop_index(op.f('ix_resolution_slas_due_at'), table_name='resolution_slas')
    op.drop_index(op.f('ix_resolution_slas_client_id'), table_name='resolution_slas')
    op.drop_table('resolution_slas')
    op.drop_table('sla_policies')
    op.drop_index('ix_sla_breach_notifications_unique', table_name='sla_breach_notifications')
    op.drop_table('sla_breach_notifications')
    # ### end Alembic commands ###