"""add ticket_edit_access_requests table

Revision ID: 34c63a9d3ef2
Revises: a7ad0a59b85f
Create Date: 2026-07-08 20:12:44.052575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '34c63a9d3ef2'
down_revision: Union[str, None] = 'a7ad0a59b85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_edit_access_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='edit_access_status_enum'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_ticket_edit_access_requests_pending_unique', 'ticket_edit_access_requests', ['ticket_id', 'requested_by'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_ticket_edit_access_requests_ticket_id'), 'ticket_edit_access_requests', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_edit_access_requests_ticket_id'), table_name='ticket_edit_access_requests')
    op.drop_index('ix_ticket_edit_access_requests_pending_unique', table_name='ticket_edit_access_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('ticket_edit_access_requests')
    # ### end Alembic commands ###