"""add is_draft to interactions

Revision ID: 705a2e60ebe4
Revises: a1b3c5d7e9f1
Create Date: 2026-07-08 10:20:12.972032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '705a2e60ebe4'
down_revision: Union[str, None] = 'a1b3c5d7e9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'interactions',
        sa.Column('is_draft', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('interactions', 'is_draft', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'is_draft')
    # ### end Alembic commands ###