"""add claimed_by and claimed_at to interactions

Revision ID: 8f1899cafaae
Revises: e4f6a8b0c2d4
Create Date: 2026-07-07 19:40:18.904423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '8f1899cafaae'
down_revision: Union[str, None] = 'e4f6a8b0c2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('claimed_by', sa.UUID(), nullable=True))
    op.add_column('interactions', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'interactions', 'users', ['claimed_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'claimed_at')
    op.drop_column('interactions', 'claimed_by')
    # ### end Alembic commands ###