"""add client_assignments and client_contacts tables

Revision ID: c9e1a3b5d7f0
Revises: b7d9f1a3c5e8
Create Date: 2026-08-06 00:00:00.000000

Part of the real-org-data migration (see scripts/org_seed/): the
original schema only had `clients.account_manager_id` (one owning
Account Manager per client) and no stored client contact list at all
(contacts were always computed live from ticket interactions). Real
client data needs a per-client AR/Coding/Posting Lead on top of the
Account Manager, and a list of known contact emails ahead of any
ticket ever arriving — hence these two new, additive tables. Hand-
written (not autogenerated), mirroring the column/constraint style of
b1c3d5e7f9a1_add_clients_table.py and rbac's reporting_manager_teams.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c9e1a3b5d7f0'
down_revision: Union[str, None] = 'b7d9f1a3c5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'client_assignments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('lead_role', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('client_id', 'lead_role', name='uq_client_assignment_role'),
        sa.CheckConstraint(
            "lead_role IN ('AR_LEAD', 'CODING_LEAD', 'POSTING_LEAD')",
            name='ck_client_assignment_lead_role',
        ),
    )
    op.create_index(
        op.f('ix_client_assignments_client_id'), 'client_assignments', ['client_id'],
    )
    op.create_index(
        op.f('ix_client_assignments_user_id'), 'client_assignments', ['user_id'],
    )

    op.create_table(
        'client_contacts',
        sa.Column('contact_id', sa.UUID(), nullable=False),
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('contact_id'),
        sa.UniqueConstraint('client_id', 'email', name='uq_client_contact_email'),
    )
    op.create_index(
        op.f('ix_client_contacts_client_id'), 'client_contacts', ['client_id'],
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_client_contacts_client_id'), table_name='client_contacts')
    op.drop_table('client_contacts')

    op.drop_index(op.f('ix_client_assignments_user_id'), table_name='client_assignments')
    op.drop_index(op.f('ix_client_assignments_client_id'), table_name='client_assignments')
    op.drop_table('client_assignments')
