"""add mail folders, tags, folder_id, snoozed_until

Revision ID: cdcf2019a594
Revises: 9b2c4d6e8f0a
Create Date: 2026-07-08 09:43:23.719934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdcf2019a594'
down_revision: Union[str, None] = '9b2c4d6e8f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_folders',
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('folder_id'),
    sa.UniqueConstraint('name')
    )
    # server_default backfills existing rows — this table already has
    # data, and a NOT NULL column with no default fails on an
    # existing populated table. Dropped after the column exists so
    # future inserts still rely on the ORM-level default=list instead
    # of a DB-level one staying around indefinitely.
    op.add_column(
        'interactions',
        sa.Column(
            'tags',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column('interactions', 'tags', server_default=None)
    op.add_column('interactions', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.add_column('interactions', sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'interactions', 'mail_folders', ['folder_id'], ['folder_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactions', type_='foreignkey')
    op.drop_column('interactions', 'snoozed_until')
    op.drop_column('interactions', 'folder_id')
    op.drop_column('interactions', 'tags')
    op.drop_table('mail_folders')
    # ### end Alembic commands ###