"""add user_permission_overrides table

Revision ID: 068d1db9bca5
Revises: 579d6f955206
Create Date: 2026-07-08 15:18:49.042881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068d1db9bca5'
down_revision: Union[str, None] = '579d6f955206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission_overrides',
    sa.Column('override_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('override_id')
    )
    op.create_index('ix_user_permission_overrides_active_unique', 'user_permission_overrides', ['user_id', 'permission_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # Note: autogenerate also detected a pre-existing, unrelated
    # 'role_permissions.role_name' column drift (present in the DB,
    # not declared on the RolePermission model) — deliberately left
    # untouched here since it's out of scope for this migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_index('ix_user_permission_overrides_active_unique', table_name='user_permission_overrides', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('user_permission_overrides')
    # ### end Alembic commands ###
