"""add clients table

Revision ID: b1c3d5e7f9a1
Revises: 4e6b8a1d3c5f
Create Date: 2026-07-06 00:00:00.000000

New MVP model: a client is a company with a dedicated shared inbox
address, owned by an Account Manager. Inbound email is routed by
matching its `to` address against `inbox_email` here. Hand-written
(not autogenerated) since this environment has no live DB connection
to diff against — mirrors the column/constraint style of
c6f212b05143_initial_ticket_management_schema.py.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b1c3d5e7f9a1'
down_revision: Union[str, None] = '4e6b8a1d3c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'clients',
        sa.Column('client_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('inbox_email', sa.String(length=255), nullable=False),
        sa.Column('account_manager_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['account_manager_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('client_id'),
        sa.UniqueConstraint('inbox_email'),
    )


def downgrade() -> None:
    op.drop_table('clients')
