"""add ticket_relations table

Revision ID: ca61799f538d
Revises: 705a2e60ebe4
Create Date: 2026-07-08 10:34:28.872191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ca61799f538d'
down_revision: Union[str, None] = '705a2e60ebe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_relations',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('related_ticket_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_ticket_id'], ['tickets.ticket_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'related_ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_relations')
    # ### end Alembic commands ###